-- =============================================
-- DATABASE REBUILD SCRIPT
-- CSE 340 - Assignment 2: Disaster Recovery
-- =============================================
-- This file contains the complete database structure rebuild
-- after deleting and recreating the database from Render.com
--
-- INCLUDES:
-- 1. ENUM Type creation
-- 2. All CREATE TABLE statements
-- 3. Data population (INSERT statements)
-- 4. Final queries (Query 4 and Query 6 from Assignment 2)

-- =============================================
-- STEP 1: ACCOUNT TYPE DEFINITION
-- =============================================
-- Using VARCHAR instead of ENUM for Render PostgreSQL compatibility
-- Valid values: 'Client', 'Employee', 'Admin'
-- Validation is handled in the application (Node.js)

-- =============================================
-- STEP 2: DROP EXISTING TABLES (if rebuilding)
-- =============================================
-- Removes tables in correct order (dependencies first)
-- CASCADE ensures dependent tables are also removed

DROP TABLE IF EXISTS inventory CASCADE;
DROP TABLE IF EXISTS classification CASCADE;
DROP TABLE IF EXISTS account CASCADE;

-- =============================================
-- STEP 3: CREATE TABLE - classification
-- =============================================
-- Stores vehicle classification types
-- Supports proper database normalization
-- Allows categorization of inventory by type

CREATE TABLE IF NOT EXISTS public.classification (
  classification_id SERIAL PRIMARY KEY,
  classification_name VARCHAR(50) NOT NULL UNIQUE
);

-- =============================================
-- STEP 4: CREATE TABLE - inventory
-- =============================================
-- Stores vehicle records with detailed information
-- Foreign key relationship to classification table
-- Supports vehicle images and pricing information

CREATE TABLE IF NOT EXISTS public.inventory (
  inv_id SERIAL PRIMARY KEY,
  inv_make VARCHAR(50) NOT NULL,
  inv_model VARCHAR(50) NOT NULL,
  inv_year INTEGER NOT NULL,
  inv_description TEXT NOT NULL,
  inv_image VARCHAR(200) NOT NULL,
  inv_thumbnail VARCHAR(200) NOT NULL,
  inv_price NUMERIC(9,2) NOT NULL,
  inv_miles INTEGER NOT NULL DEFAULT 0,
  inv_color VARCHAR(30) NOT NULL,
  classification_id INTEGER NOT NULL,
  CONSTRAINT fk_classification
    FOREIGN KEY (classification_id)
    REFERENCES public.classification(classification_id)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);

-- =============================================
-- STEP 5: CREATE TABLE - account
-- =============================================
-- Stores user account information
-- Supports client authentication and user management
-- account_type defaults to 'Client' for new accounts
-- Using VARCHAR for account_type (ENUM not supported on Render free tier)

CREATE TABLE IF NOT EXISTS public.account (
  account_id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  account_firstname VARCHAR NOT NULL,
  account_lastname VARCHAR NOT NULL,
  account_email VARCHAR NOT NULL,
  account_password VARCHAR NOT NULL,
  account_type VARCHAR(20) NOT NULL DEFAULT 'Client',
  CONSTRAINT account_pkey PRIMARY KEY (account_id)
);

-- =============================================
-- STEP 6: INSERT DATA - classification
-- =============================================
-- Populates vehicle classification types
-- Used to categorize and filter vehicles

INSERT INTO public.classification (classification_name) VALUES
  ('Custom'),
  ('Sport'),
  ('SUV'),
  ('Truck'),
  ('Sedan');

-- =============================================
-- STEP 7: INSERT DATA - inventory
-- =============================================
-- Populates vehicle inventory with sample data
-- Includes 6 vehicles across different categories
-- All images are stored in /images/vehicles/ directory

INSERT INTO public.inventory (
  inv_make,
  inv_model,
  inv_year,
  inv_description,
  inv_image,
  inv_thumbnail,
  inv_price,
  inv_miles,
  inv_color,
  classification_id
) VALUES
  -- Veículo 1: DMC Delorean (Custom)
  (
    'DMC',
    'Delorean',
    1981,
    'The DMC DeLorean is a rear-engine two-passenger sports car manufactured and marketed by John DeLorean''s DeLorean Motor Company (DMC) for the American market from 1981–83. The car features gull-wing doors and a stainless-steel outer body shell.',
    '/images/vehicles/delorean.jpg',
    '/images/vehicles/delorean-tn.jpg',
    35000.00,
    3000,
    'Silver',
    1
  ),

  -- Veículo 2: Ford Model T (Custom)
  (
    'Ford',
    'Model T',
    1908,
    'The Ford Model T is an automobile that was produced by Ford Motor Company from October 1, 1908, to May 26, 1927. It is generally regarded as the first affordable automobile, which made car travel available to middle-class Americans.',
    '/images/vehicles/model-t.jpg',
    '/images/vehicles/model-t-tn.jpg',
    15000.00,
    50000,
    'Black',
    1
  ),

  -- Veículo 3: Jeep Wrangler (SUV)
  (
    'Jeep',
    'Wrangler',
    2019,
    'The Jeep Wrangler is a series of compact and mid-size four-wheel drive off-road SUVs manufactured by Jeep since 1986. Features removable doors and top for open-air driving.',
    '/images/vehicles/wrangler.jpg',
    '/images/vehicles/wrangler-tn.jpg',
    28000.00,
    41000,
    'Orange',
    3
  ),

  -- Veículo 4: Chevrolet Camaro (Sport)
  (
    'Chevrolet',
    'Camaro',
    2022,
    'The Chevrolet Camaro is a mid-size American automobile manufactured by Chevrolet, classified as a pony car. It went on sale on September 29, 1966, for the 1967 model year.',
    '/images/vehicles/camaro.jpg',
    '/images/vehicles/camaro-tn.jpg',
    42000.00,
    8000,
    'Yellow',
    2
  ),

  -- Veículo 5: Ford F-150 (Truck)
  (
    'Ford',
    'F-150',
    2023,
    'The Ford F-Series is a series of trucks marketed and manufactured by Ford Motor Company since 1948. The F-150 is the most popular variant of the F-Series, and is the best-selling vehicle in the United States.',
    '/images/vehicles/f150.jpg',
    '/images/vehicles/f150-tn.jpg',
    55000.00,
    12000,
    'Blue',
    4
  ),

  -- Veículo 6: GM Hummer (SUV)
  -- NOTE: This vehicle has "small interiors" in description for Query 4 REPLACE
  (
    'GM',
    'Hummer',
    2016,
    'The Hummer is a great vehicle for those who need a lot of space. It comes with seating for many passengers and small interiors. The car is very capable of towing, hauling, and general off road driving.',
    '/images/vehicles/hummer.jpg',
    '/images/vehicles/hummer-tn.jpg',
    35000.00,
    37000,
    'Yellow',
    3
  );

-- =============================================
-- STEP 8: CREATE INDEXES for performance
-- =============================================
-- Indexes on frequently queried columns
-- Improves query performance on large datasets

CREATE INDEX IF NOT EXISTS idx_inventory_classification ON public.inventory(classification_id);
CREATE INDEX IF NOT EXISTS idx_inventory_make ON public.inventory(inv_make);

-- =============================================
-- STEP 9: ADD COMMENTS for documentation
-- =============================================
-- Metadata comments visible in database tools
-- Helps other developers understand the schema

COMMENT ON TABLE public.classification IS 'Vehicle classification types (Custom, Sport, SUV, Truck, Sedan)';
COMMENT ON TABLE public.inventory IS 'Vehicle inventory with pricing and description data';
COMMENT ON TABLE public.account IS 'User account records with authentication information';

-- =============================================
-- STEP 10: FINAL OPERATIONS - Assignment 2 Queries 4 & 6
-- =============================================
-- These queries are executed as part of the database rebuild
-- to demonstrate Assignment 2 requirements completion

-- =============================================
-- QUERY 4: UPDATE with REPLACE - Fix GM Hummer description
-- =============================================
-- Replaces "small interiors" with "a huge interior"
-- This query demonstrates proper use of PostgreSQL REPLACE function
-- Assignment 2 Requirement: Modify inventory using REPLACE()

UPDATE public.inventory
SET inv_description = REPLACE(inv_description, 'small interiors', 'a huge interior')
WHERE inv_make = 'GM' AND inv_model = 'Hummer';

-- =============================================
-- QUERY 6: UPDATE with Path Modification
-- =============================================
-- Adds "/vehicles" to the middle of file paths
-- Updates both inv_image and inv_thumbnail columns
-- Transforms '/images/delorean.jpg' to '/images/vehicles/delorean.jpg'

UPDATE public.inventory
SET
    inv_image = REPLACE(inv_image, '/images/', '/images/vehicles/'),
    inv_thumbnail = REPLACE(inv_thumbnail, '/images/', '/images/vehicles/')
WHERE inv_image NOT LIKE '%/vehicles/%'
  AND inv_thumbnail NOT LIKE '%/vehicles/%';

-- =============================================
-- DATABASE REBUILD COMPLETE
-- =============================================
-- The database is now ready for use with:
-- - 3 tables (classification, inventory, account)
-- - Complete seed data
-- - Proper indexes and constraints
-- - Assignment 2 final operations applied