-- =============================================
-- DATABASE REBUILD SCRIPT
-- CSE 340 - Assignment 2: Disaster Recovery
-- =============================================
-- Este arquivo contém a reconstrução completa do banco de dados
-- após deletar e recriar o banco de dados do Render.com
--
-- BASEADO EM: schema.sql (versão que funciona no Render)
-- ADICIONADO: Queries 4 e 6 do Assignment 2 para demonstração
--
-- INCLUI:
-- 1. DROP de tabelas existentes (se houver)
-- 2. Todas as statements CREATE TABLE
-- 3. População de dados (statements INSERT)
-- 4. Índices para performance
-- 5. Comentários de documentação
-- 6. Queries 4 e 6 do Assignment 2 (disaster recovery demo)

-- =============================================
-- STEP 0: CRIAR SCHEMA CUSTOMIZADO
-- =============================================
-- Cria um schema chamado 'cse340' para evitar restrições do schema 'public'
-- Render free tier tem permissões limitadas no schema public
-- A solução é usar um schema customizado

CREATE SCHEMA IF NOT EXISTS cse340;

-- =============================================
-- STEP 1: LIMPAR DADOS EXISTENTES (se houver)
-- =============================================
-- DROP = "Derrubar/Remover"
-- IF EXISTS = Só remove se a tabela existir (evita erro)
-- CASCADE = Remove em cascata (remove dependências também)
-- Ordem importa: Remover primeiro as tabelas que DEPENDEM de outras

DROP TABLE IF EXISTS cse340.inventory CASCADE;
DROP TABLE IF EXISTS cse340.classification CASCADE;
DROP TABLE IF EXISTS cse340.account CASCADE;

-- =============================================
-- STEP 2: TABELA: classification (Classificação/Tipo)
-- =============================================
-- Armazena os TIPOS de veículos (Sedan, SUV, Truck, etc)
--
-- CONCEITO: Normalização
-- ----------------------
-- Em vez de repetir "Sedan", "Sedan", "Sedan" em cada veículo,
-- criamos uma tabela separada e fazemos REFERÊNCIA ao ID.
-- Benefícios:
-- - Economiza espaço
-- - Consistência (não tem erro de digitação)
-- - Fácil de atualizar (muda em um lugar só)

CREATE TABLE cse340.classification (
  -- PRIMARY KEY (Chave Primária)
  -- SERIAL = Auto-incrementa automaticamente: 1, 2, 3...
  -- PRIMARY KEY = Identifica UNICAMENTE cada registro
  classification_id SERIAL PRIMARY KEY,

  -- VARCHAR(50) = String de até 50 caracteres
  -- NOT NULL = Campo obrigatório (não pode estar vazio)
  -- UNIQUE = Não pode repetir (ex: não pode ter dois "Sedan")
  classification_name VARCHAR(50) NOT NULL UNIQUE
);

-- =============================================
-- STEP 3: TABELA: inventory (Inventário/Estoque)
-- =============================================
-- Armazena os VEÍCULOS disponíveis no estoque
--
-- CONCEITO: Foreign Key (Chave Estrangeira)
-- classification_id nesta tabela "aponta para" classification_id na tabela classification
-- Isso cria um RELACIONAMENTO: "Um veículo pertence a uma classificação"

CREATE TABLE cse340.inventory (
  -- Primary Key desta tabela
  inv_id SERIAL PRIMARY KEY,

  -- Informações básicas do veículo
  inv_make VARCHAR(50) NOT NULL,        -- Fabricante (ex: Toyota, Ford)
  inv_model VARCHAR(50) NOT NULL,       -- Modelo (ex: Camry, F-150)
  inv_year INTEGER NOT NULL,            -- Ano (ex: 2020, 2023)

  -- Descrição detalhada
  inv_description TEXT NOT NULL,        -- TEXT = String sem limite de tamanho

  -- Imagem do veículo
  inv_image VARCHAR(200) NOT NULL,      -- Caminho para a imagem
  inv_thumbnail VARCHAR(200) NOT NULL,  -- Miniatura (versão pequena da imagem)

  -- Preço e milhagem
  -- NUMERIC(9,2) = Número decimal com até 9 dígitos, 2 após o ponto
  inv_price NUMERIC(9,2) NOT NULL,      -- Preço (ex: 35000.00)
  inv_miles INTEGER NOT NULL DEFAULT 0, -- Milhagem (ex: 15000)

  -- Cor do veículo
  inv_color VARCHAR(30) NOT NULL,       -- Cor (ex: "Silver", "Black")

  -- FOREIGN KEY (Chave Estrangeira)
  -- Este campo cria a RELAÇÃO com a tabela classification
  classification_id INTEGER NOT NULL,

  -- CONSTRAINT = Restrição/Regra
  -- ON DELETE CASCADE = Se deletar uma classification, deleta veículos dessa classificação
  -- ON UPDATE CASCADE = Se mudar o ID, atualiza automaticamente aqui
  CONSTRAINT fk_classification
    FOREIGN KEY (classification_id)
    REFERENCES cse340.classification(classification_id)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);

-- =============================================
-- STEP 4: TABELA: account (Contas de Usuário)
-- =============================================
-- Armazena as contas dos usuários do sistema
-- GENERATED BY DEFAULT AS IDENTITY = Auto-incrementa o ID
-- account_type = Tipo de conta (Client, Employee, Admin)

CREATE TABLE cse340.account (
  -- Primary Key desta tabela
  -- GENERATED BY DEFAULT AS IDENTITY = Auto-incrementa automaticamente
  account_id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,

  -- Informações pessoais
  account_firstname VARCHAR NOT NULL,       -- Primeiro nome (ex: Tony, John)
  account_lastname VARCHAR NOT NULL,        -- Sobrenome (ex: Stark, Doe)

  -- Informações de contato
  account_email VARCHAR NOT NULL,           -- Email (ex: tony@starkent.com)

  -- Senha (será hasheada em produção!)
  account_password VARCHAR NOT NULL,        -- Senha criptografada

  -- Tipo de conta
  -- VARCHAR ao invés de ENUM (compatibilidade com Render)
  -- Valores válidos: 'Client', 'Employee', 'Admin'
  account_type VARCHAR(20) NOT NULL DEFAULT 'Client',

  -- Definir primary key
  CONSTRAINT account_pkey PRIMARY KEY (account_id)
);

-- =============================================
-- STEP 5: INSERIR DADOS - classification
-- =============================================
-- Popula os tipos de classificação de veículos
-- Usado para categorizar e filtrar veículos

INSERT INTO cse340.classification (classification_name) VALUES
  ('Custom'),
  ('Sport'),
  ('SUV'),
  ('Truck'),
  ('Sedan');

-- =============================================
-- STEP 6: INSERIR DADOS - inventory
-- =============================================
-- Popula o inventário de veículos com dados de exemplo
-- Inclui 6 veículos em diferentes categorias

INSERT INTO cse340.inventory (
  inv_make,
  inv_model,
  inv_year,
  inv_description,
  inv_image,
  inv_thumbnail,
  inv_price,
  inv_miles,
  inv_color,
  classification_id
) VALUES
  -- Veículo 1: DMC Delorean (Custom)
  (
    'DMC',
    'Delorean',
    1981,
    'The DMC DeLorean is a rear-engine two-passenger sports car manufactured and marketed by John DeLorean''s DeLorean Motor Company (DMC) for the American market from 1981–83. The car features gull-wing doors and a stainless-steel outer body shell.',
    '/images/vehicles/delorean.jpg',
    '/images/vehicles/delorean-tn.jpg',
    35000.00,
    3000,
    'Silver',
    1
  ),

  -- Veículo 2: Ford Model T (Custom)
  (
    'Ford',
    'Model T',
    1908,
    'The Ford Model T is an automobile that was produced by Ford Motor Company from October 1, 1908, to May 26, 1927. It is generally regarded as the first affordable automobile, which made car travel available to middle-class Americans.',
    '/images/vehicles/model-t.jpg',
    '/images/vehicles/model-t-tn.jpg',
    15000.00,
    50000,
    'Black',
    1
  ),

  -- Veículo 3: Jeep Wrangler (SUV)
  (
    'Jeep',
    'Wrangler',
    2019,
    'The Jeep Wrangler is a series of compact and mid-size four-wheel drive off-road SUVs manufactured by Jeep since 1986. Features removable doors and top for open-air driving.',
    '/images/vehicles/wrangler.jpg',
    '/images/vehicles/wrangler-tn.jpg',
    28000.00,
    41000,
    'Orange',
    3
  ),

  -- Veículo 4: Chevrolet Camaro (Sport)
  (
    'Chevrolet',
    'Camaro',
    2022,
    'The Chevrolet Camaro is a mid-size American automobile manufactured by Chevrolet, classified as a pony car. It went on sale on September 29, 1966, for the 1967 model year.',
    '/images/vehicles/camaro.jpg',
    '/images/vehicles/camaro-tn.jpg',
    42000.00,
    8000,
    'Yellow',
    2
  ),

  -- Veículo 5: Ford F-150 (Truck)
  (
    'Ford',
    'F-150',
    2023,
    'The Ford F-Series is a series of trucks marketed and manufactured by Ford Motor Company since 1948. The F-150 is the most popular variant of the F-Series, and is the best-selling vehicle in the United States.',
    '/images/vehicles/f150.jpg',
    '/images/vehicles/f150-tn.jpg',
    55000.00,
    12000,
    'Blue',
    4
  ),

  -- Veículo 6: GM Hummer (SUV) - NECESSÁRIO PARA ASSIGNMENT 2
  -- Este veículo tem "small interiors" na descrição para a query REPLACE
  (
    'GM',
    'Hummer',
    2016,
    'The Hummer is a great vehicle for those who need a lot of space. It comes with seating for many passengers and small interiors. The car is very capable of towing, hauling, and general off road driving.',
    '/images/vehicles/hummer.jpg',
    '/images/vehicles/hummer-tn.jpg',
    35000.00,
    37000,
    'Yellow',
    3
  );

-- =============================================
-- STEP 7: CRIAR ÍNDICES (para performance)
-- =============================================
-- CONCEITO: Índice (Index)
-- Como o índice de um livro: ajuda a encontrar coisas mais rápido
-- Útil em colunas que você vai BUSCAR frequentemente

-- Índice na coluna classification_id da tabela inventory
-- Acelera queries como: SELECT * FROM inventory WHERE classification_id = 1
CREATE INDEX idx_inventory_classification ON cse340.inventory(classification_id);

-- Índice na coluna inv_make (fabricante)
-- Acelera queries como: SELECT * FROM inventory WHERE inv_make = 'Ford'
CREATE INDEX idx_inventory_make ON cse340.inventory(inv_make);

-- =============================================
-- STEP 8: ADICIONAR COMENTÁRIOS (documentação)
-- =============================================
-- PostgreSQL permite adicionar comentários às tabelas e colunas
-- Isso aparece em ferramentas de administração (pgAdmin, DBeaver, etc)

COMMENT ON TABLE cse340.classification IS 'Tipos/Categorias de veículos (Custom, Sport, SUV, etc)';
COMMENT ON TABLE cse340.inventory IS 'Inventário de veículos disponíveis para venda';
COMMENT ON TABLE cse340.account IS 'Contas de usuário do sistema (clientes, funcionários, admin)';

-- =============================================
-- STEP 9: OPERAÇÕES FINAIS - Queries 4 & 6 do Assignment 2
-- =============================================
-- Estas queries são executadas como parte da reconstrução do banco
-- para demonstrar os requisitos do Assignment 2

-- =============================================
-- QUERY 4: UPDATE com REPLACE - Corrigir descrição do GM Hummer
-- =============================================
-- Substitui "small interiors" por "a huge interior"
-- Esta query demonstra o uso apropriado da função REPLACE do PostgreSQL
-- Requisito Assignment 2: Modificar inventory usando REPLACE()

UPDATE cse340.inventory
SET inv_description = REPLACE(inv_description, 'small interiors', 'a huge interior')
WHERE inv_make = 'GM' AND inv_model = 'Hummer';

-- =============================================
-- QUERY 6: UPDATE com Modificação de Caminho
-- =============================================
-- Adiciona "/vehicles" no meio dos caminhos de arquivo
-- Transforma '/images/delorean.jpg' em '/images/vehicles/delorean.jpg'
-- Transforma '/images/delorean-tn.jpg' em '/images/vehicles/delorean-tn.jpg'
-- Usa a função REPLACE() para inserir um diretório no caminho
-- Aplicada a ambas as colunas inv_image e inv_thumbnail de todos os registros

UPDATE cse340.inventory
SET
    inv_image = REPLACE(inv_image, '/images/', '/images/vehicles/'),
    inv_thumbnail = REPLACE(inv_thumbnail, '/images/', '/images/vehicles/')
WHERE inv_image NOT LIKE '%/vehicles/%'
  AND inv_thumbnail NOT LIKE '%/vehicles/%';

-- =============================================
-- RECONSTRUÇÃO DO BANCO DE DADOS COMPLETA
-- =============================================
-- O banco de dados agora está pronto para uso com:
-- - 3 tabelas (classification, inventory, account)
-- - Dados completos e seed data
-- - Índices apropriados e constraints
-- - Operações finais do Assignment 2 aplicadas
-- - Disaster recovery demonstrado com sucesso